# custom nginx config to how to respond to incoming requests inside client container

# start server block, a configuration for one app
server {
  # listens for other containers on client:8080
  listen 8080;
  # specify to use this config for requests that reach this server
  server_name _;
  # where the frontend files live
  root /usr/share/nginx/html;
  # serve index.html for /
  index index.html;

  # if request path starts with /api/, don't server a frontend file, but forward it to the flask container
  location /api/ {
    # forwarding to server:5500
    proxy_pass http://server:5500/api/;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
  }

  # handle frontend file requests
  location / {
    # first check whether the requests file actually exists. If so, serve it
    # if not, serve index.html
    try_files $uri /index.html;
  }
}
